-- Select of all tables
SELECT * FROM [tbl_App]
SELECT * FROM [tbl_Module]
SELECT * FROM [tbl_User]
SELECT * FROM [tbl_User_history]
SELECT * FROM [tbl_Audit_User]
SELECT * FROM [tbl_Role]
SELECT * FROM [tbl_Permission]
SELECT * FROM [tbl_Resource]
SELECT * FROM [tbl_User_App]
SELECT * FROM [tbl_User_Role]
SELECT * FROM [tbl_Role_Role]
SELECT * FROM [tbl_Role_Permission]
SELECT * FROM [tbl_Permission_Resource]
SELECT * FROM [tbl_Module_Resource]
SELECT * FROM [tbl_Sessions]