name: api-gateway-build-push
on:
  push:
    paths:
    - 'api-gateway/**'

    branches:
      - main 
  workflow_dispatch: 

permissions:
  id-token: write
  contents: read  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:                       
      - uses: actions/checkout@v2                  
      - name: Login to Dockerhub
        id: docker-hub
        env:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
        run: |
            docker login -u $username -p $password 

      - name: Docker Build and Publish
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./api-gateway/Dockerfile
          push: true
          tags: umg100/api-gateway:${{github.run_number}}